
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module S13390613_3(

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
assign HEX0 = {g,f,e,d,c,b,a};

wire [2:0] q_out;//counter out
wire [7:0] Yo;//decoder out
wire D3, D2, D1, D0;//moniter in
 
//instantiate mod-8 up counter with reset
mod_8_up_reset_behavioral		chip1(.clk(KEY[3]), .q_out(q_out));
//instantiate 7 segment decoder with inverting output

bin_7seg_decoder_inv_dataflow chip2 (.D3(D3), .D2(D2), .D1(D1), .D0(D0),
												 .a(a), .b(b), .c(c), .d(d), .e(e), .f(f), .g(g)); 

//instantiate 3-to-8 decoder with inverting output
decoder_3to8_Enable_behavioral chip3 (.x_in(q_out), .y_out(Yo), .Enable(1'b0));											 
//=======================================================
//  Structural coding
//=======================================================
//student number
reg [3:0] digits [0:7];
initial begin
    digits[0] = 4'd1;
    digits[1] = 4'd3;
    digits[2] = 4'd3;
    digits[3] = 4'd9;
    digits[4] = 4'd0;
    digits[5] = 4'd6;
    digits[6] = 4'd1;
    digits[7] = 4'd3;
end

wire [3:0] current_digit = digits[q_out];

assign D3 = current_digit[3];
assign D2 = current_digit[2];
assign D1 = current_digit[1];
assign D0 = current_digit[0];
endmodule
